In [6]:
import numpy as np

a = np.array([[1, 2, 4], [5, 8, 7]])

print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [3]:
b = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", b)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
d = np.random.random((2, 2))
print ("\nA random array:\n", d)


A random array:
 [[0.74222091 0.85348475]
 [0.67074727 0.3412001 ]]


In [5]:
arr = np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshape array[4,3]:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshape array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [7]:
print("\nN0.of.dimensions:",arr.ndim)


N0.of.dimensions: 2


In [8]:
print("\nShape of array: ", arr.shape)


Shape of array:  (3, 4)


In [9]:
print("\nSize of array: ", arr.size)


Size of array:  12


In [10]:
print("\nArray stores elements of type: ",
arr.dtype)


Array stores elements of type:  int32


In [11]:
flarr = arr.flatten()
print("\nOriginal array:\n",arr)
print("Flattened array:\n",flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [12]:
newtype=arr.astype('f')
print("\nConverted array elements:\n",newtype)
print("Converted array type:",newtype.dtype)


Converted array elements:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float32


In [28]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print (arr)
print (arr[[4, 3, 0, 6]])
print (arr[[-3, -5, -7]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [29]:
arr = np.arange(15).reshape((3, 5))
print (arr)
print (arr.shape)
print (arr.T)
print (arr.T.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(5, 3)


In [31]:
arr = np.array([[1, 2, 3, 4],[5, 2, 4, 2],[3, 5, 8, 9],[5, 9, 2, 0],[1, 2, 0, 1]])
print("every alternate row\n",arr[0:4:2])
print("first 2 rows and 3 columns\n",arr[:2,:3])
print("except first 2 rows and 2columns\n",arr[2:,2:])
print("extracting 2nd row, 3rd value\n",arr[2,3])
print("first 2 rows\n", arr[:2])
print("except first 3 rows\n",arr[3:])
print("first 3 columns\n",arr[:,:3])

every alternate row
 [[1 2 3 4]
 [3 5 8 9]]
first 2 rows and 3 columns
 [[1 2 3]
 [5 2 4]]
except first 2 rows and 2columns
 [[8 9]
 [2 0]
 [0 1]]
extracting 2nd row, 3rd value
 9
first 2 rows
 [[1 2 3 4]
 [5 2 4 2]]
except first 3 rows
 [[5 9 2 0]
 [1 2 0 1]]
first 3 columns
 [[1 2 3]
 [5 2 4]
 [3 5 8]
 [5 9 2]
 [1 2 0]]


In [32]:
print("Original array:\n", arr)
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
"(3, 0):\n", temp)

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [3 5 8 9]
 [5 9 2 0]
 [1 2 0 1]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4 4 5 5]


In [35]:
cond = arr>2
temp = arr[cond]
print("\nElements greater than 2:\n",temp)


Elements greater than 2:
 [3 4 5 4 3 5 8 9 5 9]


In [36]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print("\nOriginal arrays:\n",arr1,arr2)
print("\nJoined array:\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

Joined array:
 [1 2 3 4 5 6]


In [37]:
arr = np.hstack((arr1, arr2))
print("\horizontal joining:\n",arr)

\horizontal joining:
 [1 2 3 4 5 6]


In [38]:
print("\nOriginal arrays:\n",arr1,arr2)

arr = np.vstack((arr1, arr2))
print("\nVertical joining:\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [39]:
arr = np.dstack((arr1, arr2))
print("\nDepth joining:\n",arr)


Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [40]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print("\nOriginal Array:\n",arr)
print("\nSplitted array:\n",newarr)


Original Array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [41]:
print("\nSplit array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


Split array in another form:

[1 2]
[3 4]
[5 6]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print("Original array:",arr)
x = np.where(arr == 4)
print("\nIndexes where the value is 4:",x)

Original array: [1 2 3 4 5 4 4]

Indexes where the value is 4: (array([3, 5, 6], dtype=int64),)


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print("\nOriginal array:",arr)
print("\nIndexes where the values are even:",x)


Original array: [1 2 3 4 5 6 7 8]

Indexes where the values are even: (array([1, 3, 5, 7], dtype=int64),)


In [48]:
arr = np.array([3,2,0,1])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))


Original array: [3 2 0 1]

Sorted array: [0 1 2 3]


In [49]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))


Original array: [[3 2 4]
 [5 0 1]]

Sorted array: [[2 3 4]
 [0 1 5]]


In [53]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition- >42:",filter_arr)
print("\nNew array:",newarr)
arr1=[10,20,30,40,50] 
arr2=[2,4,5,8,10]
a=np.array(arr1) 
b=np.array(arr2)
print("Original arrays")
print(a) 
print(b)

print("\nVector addition")
print(a+b)
print("\nVector subtraction")
print(a-b)
print("\nVector multiplication")
print(a*b)

print("\nVector division")
print(a/b)
print("\nVector Dot product")
print(a.dot(b))


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]

Original array: [41 42 43 44]

Filter array:condition- >42: [False False  True  True]

New array: [43 44]
Original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]

Vector addition
[12 24 35 48 60]

Vector subtraction
[ 8 16 25 32 40]

Vector multiplication
[ 20  80 150 320 500]

Vector division
[5. 5. 6. 5. 5.]

Vector Dot product
1070


In [55]:
print("\nScalar multiplication")
sclr=5
print(" scalar value=",sclr)
print(" array=",a)
print(" result=",a*sclr)


Scalar multiplication
 scalar value= 5
 array= [10 20 30 40 50]
 result= [ 50 100 150 200 250]
